name: fitness
description: Una nueva aplicación Flutter.

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^0.13.4
  json_annotation: ^4.4.0
  flutter_svg: ^1.0.0
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.1.7
  json_serializable: ^6.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
