@host=http://localhost:5020

PUT {{host}}/quantityRestrictions
Content-Type: application/json

{
    "UpdateModel": {
        "isActive": true
    },
    "id": "2908ada6-0610-4f78-a7d9-59c462dbde68"
}
