@host=http://localhost:5020

POST {{host}}/coincidenceRestrictions
Content-Type: application/json

{
    "CreateModel": {
        "sessionsGap": 2,
        "firstSportId": "5beb71b2-b94f-4ceb-a6bc-004ca93b07a9",
        "secondSportId" : "a06dfb42-551a-4986-9629-4a947266921b",
        "calendarId": "4c116b13-9e72-4a0d-87a6-ea01c174627a"
   }
}
