version: '3.8'

services:
  server:
    build:
      context: .
      target: final
    ports:
      - 5000:8080
    depends_on:
      db: 
        condition: service_healthy
  db:
    image: postgis/postgis:13-3.1-alpine
    restart: unless-stopped
    user: postgres
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=calendar_builder
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password  
    ports:
      - 6000:5432
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

  flutter:
    image: cirrusci/flutter:latest
    volumes:
      - ../fitness:/app
    working_dir: /app
    ports:
      - 3000:3000 
    command: flutter run --web --host-web-server=0.0.0.0 --web-port=3000
    depends_on:
      - db
      
volumes:
  db-data:
secrets:
  db-password:
    file: db/password.txt